export const useMapData = () => {
  const chapters = [
    {
      id: 1,
      title: "Chapter 1: Foundations",
      x: 800,
      y: 1500,
      width: 800,
      height: 600,
      color: "hsl(180 100% 50%)",
    },
    {
      id: 2,
      title: "Chapter 2: Advanced Concepts",
      x: 2000,
      y: 1200,
      width: 900,
      height: 700,
      color: "hsl(280 80% 60%)",
    },
    {
      id: 3,
      title: "Chapter 3: Mastery",
      x: 3200,
      y: 1600,
      width: 700,
      height: 600,
      color: "hsl(40 100% 60%)",
    },
  ];

  const nodes = [
    // Chapter 1 nodes
    {
      id: "1-1",
      x: 600,
      y: 1400,
      title: "Introduction",
      status: "completed" as const,
      chapter: 1,
      description: "Basic concepts and overview of the subject matter",
      connections: ["1-2"],
    },
    {
      id: "1-2",
      x: 750,
      y: 1300,
      title: "Core Principles",
      status: "completed" as const,
      chapter: 1,
      description: "Fundamental principles that form the foundation",
      connections: ["1-3", "1-4"],
    },
    {
      id: "1-3",
      x: 900,
      y: 1400,
      title: "Basic Methods",
      status: "current" as const,
      chapter: 1,
      description: "Learn the essential techniques and approaches",
      connections: ["1-5"],
    },
    {
      id: "1-4",
      x: 850,
      y: 1550,
      title: "Theory",
      status: "completed" as const,
      chapter: 1,
      description: "Theoretical framework and conceptual models",
      connections: ["1-5"],
    },
    {
      id: "1-5",
      x: 1000,
      y: 1500,
      title: "Practice",
      status: "locked" as const,
      chapter: 1,
      description: "Apply knowledge through practical exercises",
      connections: ["2-1"],
    },

    // Chapter 2 nodes
    {
      id: "2-1",
      x: 1600,
      y: 1200,
      title: "Complex Systems",
      status: "locked" as const,
      chapter: 2,
      description: "Understanding multi-layered systems",
      connections: ["2-2", "2-3"],
    },
    {
      id: "2-2",
      x: 1900,
      y: 1100,
      title: "Integration",
      status: "locked" as const,
      chapter: 2,
      description: "Combining concepts from previous chapters",
      connections: ["2-4"],
    },
    {
      id: "2-3",
      x: 1850,
      y: 1300,
      title: "Optimization",
      status: "locked" as const,
      chapter: 2,
      description: "Refining techniques for better results",
      connections: ["2-4"],
    },
    {
      id: "2-4",
      x: 2100,
      y: 1200,
      title: "Analysis",
      status: "locked" as const,
      chapter: 2,
      description: "Deep dive into analytical approaches",
      connections: ["2-5"],
    },
    {
      id: "2-5",
      x: 2300,
      y: 1300,
      title: "Synthesis",
      status: "locked" as const,
      chapter: 2,
      description: "Creating new solutions from learned concepts",
      connections: ["3-1"],
    },

    // Chapter 3 nodes
    {
      id: "3-1",
      x: 2900,
      y: 1500,
      title: "Expert Techniques",
      status: "locked" as const,
      chapter: 3,
      description: "Advanced methods for complex problems",
      connections: ["3-2"],
    },
    {
      id: "3-2",
      x: 3100,
      y: 1400,
      title: "Innovation",
      status: "locked" as const,
      chapter: 3,
      description: "Developing creative solutions",
      connections: ["3-3"],
    },
    {
      id: "3-3",
      x: 3250,
      y: 1550,
      title: "Application",
      status: "locked" as const,
      chapter: 3,
      description: "Real-world implementation",
      connections: ["3-4"],
    },
    {
      id: "3-4",
      x: 3400,
      y: 1650,
      title: "Mastery",
      status: "locked" as const,
      chapter: 3,
      description: "Complete understanding and expertise",
      connections: [],
    },
  ];

  return { chapters, nodes };
};
